def postArtifactManagement(Map pipelineParams) {
   echo "INFO - Using custom DevOps postArtifactManagement Processing"

   if (pipelineParams.STATIC_CODE_ANALYSIS_CHOICE == 'spotbugs_pom') {
      // archive the results generated by spotbugs
      archiveArtifacts allowEmptyArchive: true, artifacts: "target/site/spotbugs.html"
      archiveArtifacts allowEmptyArchive: true, artifacts: "target/site/spotbugs.xml"
   }
}
return this