try {
   library identifier: "devops-pipelines_branch@${env.PIPELINE_VERSION}",
      retriever: modernSCM(
         [
            $class: 'GitSCMSource',
            remote: 'https://lnsvr0329.gcsd.harris.com:8443/bitbucket/scm/devp/devops-pipelines.git',
         ]
     )
}
catch(Exception e) {
   echo "WARNING - tried to load shared pipeline library version: ${env.PIPELINE_VERSION}, but branch/tag does not exist in library repo. Using master instead."
   library identifier: "devops-pipelines@master",
      retriever: modernSCM(
         [
            $class: 'GitSCMSource', 
            remote: 'https://lnsvr0329.gcsd.harris.com:8443/bitbucket/scm/devp/devops-pipelines.git',
         ]
     )
}

runPipeline(
    //machine that the jenkins pipeline will run on. required
    JENKINS_AGENT: 'JENKINS_AGENT',

    //parameter that controls whether notifications will be sent when the job is completed. Default is 'false'. If 'true', default processing is to 
    //send an email to the user that submitted the job, and to any email addresses (comma separated list) in the EMAIL_RECIPIENTS parameter on the job.
    SEND_NOTIFICATION: 'true',

    //root of source code. optional. recommended value is '.'
    PROJECT_ROOT: '.',

   //location of the source code. optional. recommended value is 'src'
    SOURCE_CODE_DIRECTORY: 'src',

    //if you want the build tool to run. optional. recommended value is 'true'. Must be String value.
    RUN_BUILD: 'true',
    //build tool for the project. required. 'setuptools' for python, 'maven' for java, 'make' for c++, 'msbuild' for c#                    
    BUILD_TOOL: 'maven',

    //if you want to run unit tests. optional. recommended value is 'true'. Must be String value.
    RUN_UNIT_TEST: 'true',
    //unit testing framework options: VSTest, GoogleTest, JUnit, pytest, or unittest. required.
    UNIT_TEST_CHOICE: 'JUnit',
    //upload unit test results to Zephyr server. optional. Only works when the unit test is JUnit.
    PUBLISH_TO_ZEPHYR: 'true',
    //creates folder structure for test cases. optional. Must be a string value.
    ZEPHYR_CREATE_PACKAGE: 'false',
    //cycle duration will be that of the existing cycle in Zephyr. optional.
    ZEPHYR_CYCLE_DURATION: '30 days',
    //an existing cycle in Zephyr or a new cycle. optional.
    ZEPHYR_CYCLE_KEY: 'CreateNewCycle',
    //the name of the Zephyr project. required if using Zephyr. Must be a numeric string value
    ZEPHYR_PROJECT_KEY: '3',
    //the name of the Zephyr release. required if using Zephyr. Must be a numeric string value
    ZEPHYR_RELEASE_KEY: '5',
    //Zephyr server IP address or hostname. required if using Zephyr
    ZEPHYR_SERVER_ADDRESS: 'https://l3harris.zephyrdemo.com', 

    //if you want to run static code analysis. optional. recommended value is 'true'. Must be String value.
    RUN_STATIC_CODE_ANALYSIS: 'true',
    //tool used to perform static code analysis. options: SonarQube, Klocwork, CPPCheck, Pylint, spotbugs, spotbugs_cli, spotbugs_pom. required.
    STATIC_CODE_ANALYSIS_CHOICE: 'spotbugs_cli',

    //name of the html file where SpotBugs results will be saved if STATIC_CODE_ANALYSIS_CHOICE is spotbugs or spotbugs_cli
    SPOTBUGS_REPORT: 'SpotbugsReport.html',

    //If you want to run static application security testing. Optional. Recommended value is 'true'. Must be String value.
    RUN_STATIC_APPLICATION_SECURITY: 'false',

    //if you want to run code coverage. optional. recommended value is 'true'. Must be String value.
    RUN_CODE_COVERAGE: 'true',
    //options: OpenCover, OpenCppCoverage, Cobertura, JaCoCo, GCov, coverage, pytest-cov. required
    CODE_COVERAGE_CHOICE: 'jacoco',

   //if you want to run code style checking. optional. recommended value is 'true'. Must be String value.
   RUN_STYLE_CHECK: 'true',
   //options: stylecop, checkstyle
   STYLE_CHECK_CHOICE: 'Checkstyle',
   //style configuration type to be used for Checkstyle. optional. options are 'google', 'sun' or 'custom'
   STYLE_CONFIG_CHOICE: 'google',
   //custom style configuration file path for Checkstyle. optional. default value is ''
   STYLE_CONFIG_FILEPATH: '',

    //if you want to run artifact management. optional. recommended value is 'true'. Must be String value.
    RUN_ARTIFACT_MANAGEMENT: 'true',
    //artifact repository type options: Generic, NuGet, Maven, PyPi. required
    ARTIFACT_MANAGEMENT_CHOICE: 'Maven',
    //location of the artifact to store in artifact management. required      
    ARTIFACT_LOCATION: 'target',
    //name of the artifacts to store in artifact management. supports wildcards. optional. recommended value is '*'
    ARTIFACT_FILENAME_PATTERN: '*.jar',
    //location of the artifact management tool. required
    ARTIFACT_URL: 'https://lnsvr0310.gcsd.harris.com:8443/artifactory/devops_factory_maven/',
    //parent directory that the artifact will be stored in on the artifact management tool. optional. recommended value is ''
    GROUP_ID: 'Maven',
    //subdirectory that the artifact will be stored in on the artifact management tool. optional. recommended value is ''
    ARTIFACT_ID: 'HelloWorld',
    //immediate directory that the artifact will be stored in on the artifact management tool. used for versioning the artifact. optional. recommended value is '1.0.0'
    VERSION_NUMBER: '1.0.0',
    //if set to false, allows a program to append a build number to the version number. recommended value is 'false'
    FORMAL_VERSION: 'false',
    //build number that is appended to version number when deploying artifacts. optional. default value is ''
    BUILD_NUMBER: "${CUSTOM_BUILD_NUMBER}",
    //directory location for program specific pre/post processing. optional. recommended value is ''
    PROGRAM_SPECIFIC_SCRIPT: 'vars/prePostProcessing.groovy',
    
    //if you want to run artifact deployment. optional.
    RUN_DEPLOY_ARTIFACTS: 'false',

    //if you want to run functional test. optional.
    RUN_FUNCTIONAL_TEST: 'false',

    //the number of builds to keep for the job on Jenkins. optional. disabled by default.
    //Note: you are able to use both NUMBER_BUILDS_TO_KEEP and DAYS_BUILDS_TO_KEEP. If you would not like to use one, just leave it blank.
    NUMBER_BUILDS_TO_KEEP: '6',
    //the number of days worth of builds to keep for the job on Jenkins. optional. disabled by default.
    DAYS_BUILDS_TO_KEEP: '',  
    //the number of artifacts to keep for the job on Jenkins. optional. recommended value is '5'
    NUMBER_ARTIFACTS_TO_KEEP: '6',
    //the time to let the pipeline run before timing out. optional. recommended value is '9'
    TIMEOUT_TIME: 10,
    //the type of time to let the pipeline run before timing out. optional. recommended value is 'HOURS'
    TIMEOUT_UNITS: 'HOURS'
)