stage('Load Shared Library'){
try {
    library identifier: "devops-pipelines_branch@${env.PIPELINE_VERSION}",
        retriever: modernSCM(
            [
                $class: 'GitSCMSource',
                remote: 'https://xxx.xxx:8443/bitbucket/scm/devp/devops-pipelines.git',
            ]
        )
} catch(Exception e) {
    echo "WARNING - tried to load shared pipeline library version: ${env.PIPELINE_VERSION}, but branch/tag does not exist in library repo. Using master instead."
    library identifier: "devops-pipelines@master",
        retriever: modernSCM(
            [
                $class: 'GitSCMSource', 
                remote: 'https://xxx.xxx:8443/bitbucket/scm/devp/devops-pipelines.git',
            ]
        )
    }
} 

runPipeline(
    JENKINS_AGENT: 'DOCKER_REBUILD_AGENT',
  
	//parameter that controls whether notifications will be sent when the job is completed. Default is 'false'. If 'true', default processing is to 
	//send an email to the user that submitted the job, and to any email addresses (comma separated list) in the EMAIL_RECIPIENTS parameter on the job.
	SEND_NOTIFICATION: 'true',

    RUN_BUILD: 'false',
    SOURCE_CODE_DIRECTORY: "${IMAGE_NAME}/docker",
    RUN_UNIT_TEST: 'false',
    RUN_STATIC_CODE_ANALYSIS: 'false',
  	RUN_DAST: 'false',
    RUN_CODE_COVERAGE: 'false',
    RUN_ARTIFACT_MANAGEMENT: 'false',
    RUN_DEPLOY_ARTIFACTS: 'false',

    PROGRAM_SPECIFIC_SCRIPT: 'dockerProcessing.groovy',

    // Docker Specific Parameters
    REGISTRY_URL: 'https://xxx.xxx:5000',
    DOCKER_IMAGE: "${IMAGE_NAME}"
)
